### ISSUE TITLE
Simpson's paradox in regression?

### ISSUE THREAD

**Issue by cdkuempel** [GordonBlasco/GitHub-lab#1]
@GordonBlasco Looks like there might be a problem in estimating the relationship. The figure created in the chunk code beginning in [L50](https://github.com/GordonBlasco/GitHub-lab/blob/master/docs/manuscript.Rmd#L50) each species shows a clear positive trend. Perhaps we should fit three distinct lines?

**Comment by GordonBlasco** [comment]
Looks about right. I am leaving, can you take care of it?
